### PR TITLE
Use en-dash for time range instead of hyphen

### PR DESCRIPTION
**Pull request by jeffbyrnes**
Nice grammar is nice.

### CODE REVIEW

**Comment by angusmcleod** [comment]
:+1: Looks like the spacing is a bit off tho
screen shot 2017-10-23 at 8 32 43 am

**Comment by jeffbyrnes** [comment]
Ah! I’ll fix that tomorrow AM.

**Comment by jeffbyrnes** [comment]
@angusmcleod very odd; there’s no spaces in there. Any chance Moment.js is adding space?

**Comment by jeffbyrnes** [comment]
@angusmcleod any chance of a double-check of this?

**Pull request merged**
